Filter Dropdown
CMPUT301F23T08/HouseHomey pull request #31
Opened 2023-11-04 22:46 UTC by jdrco

**Summary**
- Added a filter popup menu for the dropdown
- Added a base abstract class for a filter fragment
- Added date, make, keyword, tag filter fragment sub-classes
- Initialized XML layouts for each fragment

**Preview**
![Frame 1](https://github.com/CMPUT301F23T08/HouseHomey/assets/83478026/8a4a3fb9-8bf9-4df2-91d2-ee08250ed01b)

2023-11-04 22:57 UTC, ldbonkowski requested changes
Looks awesome! My only request is that we put all the filter stuff in a folder. Things are starting to get a little crowded.

2023-11-04 23:13 UTC, owencooke commented
This is incredible dude, well done. Works exactly as we hoped.

I agree with Lukas, might be a good idea to restructure the directories. Maybe something like a `filters` directory in both the Java package and the XML res folder?

2023-11-05 00:33 UTC, jdrco commented
I have now put all fragment classes relating to filters in it's own package.

2023-11-05 01:56 UTC, ldbonkowski approved these changes

2023-11-05 01:57 UTC, merged